apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: text-pvc
      containers:
      - name: log-output-server
        image: dev-registry.localhost:5000/log-output-server
        volumeMounts:
          - name: shared
            mountPath: /usr/src/app/files
      - name: log-output-generator
        image: dev-registry.localhost:5000/log-output-generator
        volumeMounts:
          - name: shared
            mountPath: /usr/src/app/files
