apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output
  namespace: exercises
  labels:
    app: log-output
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: text-pvc
        - name: config-volume
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt
      containers:
      - name: log-output-server
        image: dev-registry.localhost:5000/log-output-server
        env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: log-output-config
                key: MESSAGE
        volumeMounts:
          - name: config-volume
            mountPath: /usr/src/app/config/information.txt
            subPath: information.txt
          - name: shared
            mountPath: /usr/src/app/files
      - name: log-output-generator
        envFrom:
          - configMapRef:
              name: log-output-generator-config
        image: dev-registry.localhost:5000/log-output-generator
        volumeMounts:
          - name: shared
            mountPath: /usr/src/app/files

