apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: pong
spec:
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: text-pvc
      containers:
      - name: pong
        image: dev-registry.localhost:5000/pong
        env:
          - name: PGUSER
            value: pongdbuser
          - name: PGPASSWORD
            value: pongdbuserpw
          - name: PGHOST
            value: db-svc
          - name: PGPORT
            value: '5432'
          - name: PGDATABASE
            value: pongdb
        volumeMounts:
          - name: shared
            mountPath: /usr/src/app/files
