apiVersion: apps/v1
kind: Deployment
metadata:
  name: pong
spec:
  selector:
    matchLabels:
      app: pong
  template:
    metadata:
      labels:
        app: pong
    spec:
      containers:
      - name: pong
        image: dev-registry.localhost:5000/pong
