apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: exercises
  name: text-pvc
spec:
  resources:
    requests:
      storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
